---
title: "Workshops"
twitter:
  creator: '@guadag12'
---

Looking to learn R for the first time or dive deeper into social network analysis? Join me in these workshops! 👇👇

### [Web Scraping and Data Collection Using RSelenium](https://github.com/guadag12/selenium-r-workshop)

During the workshop, we covered key topics such as the connection with the WebDriver, HTML sintaxis, CSS sintaxis, main functions of **Rvest** and **RSelenium* to scrape data, and how to collect that data into a data.frame. 

* [Materials here](https://github.com/guadag12/selenium-r-workshop)

### [Introduction to Data Science for Social Scientists (in spanish)](https://eant.tech/escuela-de-ciencias-de-datos/cursos/taller-data-analytics-para-ciencias-sociales)

In collaboration with @[ramaol](https://twitter.com/ramaol) , I conducted a 3-hour **free workshop** on basic R programming skills at @[EANT](https://twitter.com/eanttech) . The workshop was designed to provide participants with a solid foundation in R programming language and its application in data analysis.

During the workshop, we covered key topics such as functions, objects, importing data, data visualization, and basic regression analysis in R. Our teaching style was interactive and hands-on, with plenty of opportunities for participants to practice and apply what they learned. Join us for the course and let your comments!

* [Materials here](https://drive.google.com/drive/folders/1ZOn7k5LSAokZyBHOWbftJEMYlxMauNW2?usp=share_link)

### [Social Network Analysis using "politicxsentwitteR" (in spanish)](https://www.youtube.com/watch?v=BSU82auREmw&ab_channel=RLadiesBuenosAires)

I had the pleasure of collaborating with the incredible team at [R Ladies Buenos Aires](https://twitter.com/RLadiesBA) to present a 2-hour workshop on Social Network Analysis with R. During the workshop, we explored how to prepare data for social network analysis using the igraph package. Participants learned how to create a network, customize data, and obtain basic metrics from the network.

We also demonstrated how to use the ['politicxsentwitteR'](https://github.com/guadag12/politicxsentwitteR) package to download Twitter data and combine it with igraph to perform network analysis on social media data.

* [Materials here](https://github.com/guadag12/socialnetwork-rladies-talk)